# Generated by Django 5.0.1 on 2026-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
    ]
